security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login_index
                check_path: login_index
            logout:
                path: /logout
                target: /




# CONTROL

#    access_control:
#        - { path: ^/register, roles: PUBLIC_ACCESS }
#        - { path: ^/login, roles: PUBLIC_ACCESS }
#        - { path: ^/, roles: ROLE_USER }
